[2016-07-07 16:25:32,246] {models.py:154} INFO - Filling up the DagBag from /home/nwebz/airflow/dags/clean_opa3.py
[2016-07-07 16:25:33,361] {models.py:154} INFO - Filling up the DagBag from /home/nwebz/airflow/dags/clean_opa3.py
[2016-07-07 16:25:33,522] {models.py:1196} INFO - 
--------------------------------------------------------------------------------
Starting attempt 1 of 2
--------------------------------------------------------------------------------

[2016-07-07 16:25:33,596] {models.py:1219} INFO - Executing <Task(BashOperator): clean_buildings> on 2016-07-07 00:00:00
[2016-07-07 16:25:33,612] {bash_operator.py:55} INFO - tmp dir root location: 
/tmp
[2016-07-07 16:25:33,613] {bash_operator.py:64} INFO - Temporary script location :/tmp/airflowtmp60SPTE//tmp/airflowtmp60SPTE/clean_buildingsg6bpGs
[2016-07-07 16:25:33,613] {bash_operator.py:65} INFO - Running command: cat ~/opa_data/br63trf.buildcod | phl-building-codes > /tmp/tmpO_V7wZ/building_codes.csv
[2016-07-07 16:25:33,618] {bash_operator.py:73} INFO - Output:
[2016-07-07 16:25:33,631] {bash_operator.py:77} INFO - Traceback (most recent call last):
[2016-07-07 16:25:33,631] {bash_operator.py:77} INFO - File "/usr/local/bin/phl-building-codes", line 5, in <module>
[2016-07-07 16:25:33,631] {bash_operator.py:77} INFO - building_codes.main()
[2016-07-07 16:25:33,632] {bash_operator.py:77} INFO - File "/usr/local/lib/python2.7/dist-packages/phl_property/building_codes.py", line 35, in main
[2016-07-07 16:25:33,632] {bash_operator.py:77} INFO - writer.writerow(row)
[2016-07-07 16:25:33,632] {bash_operator.py:77} INFO - File "/usr/lib/python2.7/csv.py", line 152, in writerow
[2016-07-07 16:25:33,632] {bash_operator.py:77} INFO - return self.writer.writerow(self._dict_to_list(rowdict))
[2016-07-07 16:25:33,632] {bash_operator.py:77} INFO - IOError: [Errno 28] No space left on device
[2016-07-07 16:25:33,635] {bash_operator.py:80} INFO - Command exited with return code 1
[2016-07-07 16:25:33,635] {models.py:1286} ERROR - Bash command failed
Traceback (most recent call last):
  File "/home/nwebz/venv/local/lib/python2.7/site-packages/airflow/models.py", line 1245, in run
    result = task_copy.execute(context=context)
  File "/home/nwebz/venv/lib/python2.7/site-packages/airflow/operators/bash_operator.py", line 83, in execute
    raise AirflowException("Bash command failed")
AirflowException: Bash command failed
[2016-07-07 16:25:33,636] {models.py:1298} INFO - Marking task as UP_FOR_RETRY
[2016-07-07 16:25:33,647] {models.py:1327} ERROR - Bash command failed
